repos:
    -   repo: https://github.com/terraform-docs/terraform-docs
        rev: "v0.16.0"
        hooks:
            -   id: terraform-docs-go
                name: terraform-docs
                args: ["--config", "./documentation", ".terraform-docs.yml"]